# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

dist: "./dist"

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: osctrl-tls
    main: ./cmd/tls
    binary: "osctrl-tls-{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.Commit}}
      - -X main.buildDate={{.Date}}

  - id: osctrl-admin
    main: ./cmd/admin
    binary: "osctrl-admin-{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.Commit}}
      - -X main.buildDate={{.Date}}

  - id: osctrl-api
    main: ./cmd/api
    binary: "osctrl-api-{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.Commit}}
      - -X main.buildDate={{.Date}}

  - id: osctrl-cli
    main: ./cmd/cli
    binary: "osctrl-cli-{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Version}}
      - -X main.buildCommit={{.Commit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: osctrl
    allow_different_binary_count: true
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - osctrl-tls
      - osctrl-admin
      - osctrl-api
      - osctrl-cli
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot: {}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "{{ .Env.DOCKER_HUB_ORG }}/osctrl-tls:{{ .Version }}"
      - "{{ .Env.DOCKER_HUB_ORG }}/osctrl-tls:latest"
    dockerfile: deploy/cicd/docker/Dockerfile-osctrl-tls
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    extra_files:
      - osctrl-tls-linux-amd64
      - osctrl-tls-linux-arm64

  - image_templates:
      - "{{ .Env.DOCKER_HUB_ORG }}/osctrl-admin:{{ .Version }}"
      - "{{ .Env.DOCKER_HUB_ORG }}/osctrl-admin:latest"
    dockerfile: deploy/cicd/docker/Dockerfile-osctrl-admin
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    extra_files:
      - osctrl-admin-linux-amd64
      - osctrl-admin-linux-arm64

  - image_templates:
      - "{{ .Env.DOCKER_HUB_ORG }}/osctrl-api:{{ .Version }}"
      - "{{ .Env.DOCKER_HUB_ORG }}/osctrl-api:latest"
    dockerfile: deploy/cicd/docker/Dockerfile-osctrl-api
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    extra_files:
      - osctrl-api-linux-amd64
      - osctrl-api-linux-arm64

  - image_templates:
      - "{{ .Env.DOCKER_HUB_ORG }}/osctrl-cli:{{ .Version }}"
      - "{{ .Env.DOCKER_HUB_ORG }}/osctrl-cli:latest"
    dockerfile: deploy/cicd/docker/Dockerfile-osctrl-cli
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"
    extra_files:
      - osctrl-cli-linux-amd64
      - osctrl-cli-linux-arm64

nfpms:
  - id: osctrl-tls
    maintainer: jmpsec/osctrl
    description: osctrl TLS component
    homepage: https://github.com/jmpsec/osctrl
    license: MIT
    formats:
      - deb
    bindir: /opt/osctrl/bin
    contents:
      - src: ./dist/osctrl-tls-{{ .Os }}-{{ .Arch }}
        dst: /opt/osctrl/bin/osctrl-tls
    overrides:
      deb:
        scripts:
          postinstall: deploy/cicd/deb/post-install.sh
          preremove: deploy/cicd/deb/pre-remove.sh

  - id: osctrl-admin
    maintainer: jmpsec/osctrl
    description: osctrl Admin component
    homepage: https://github.com/jmpsec/osctrl
    license: MIT
    formats:
      - deb
    bindir: /opt/osctrl/bin
    contents:
      - src: ./dist/osctrl-admin-{{ .Os }}-{{ .Arch }}
        dst: /opt/osctrl/bin/osctrl-admin
    overrides:
      deb:
        scripts:
          postinstall: deploy/cicd/deb/post-install.sh
          preremove: deploy/cicd/deb/pre-remove.sh

  - id: osctrl-api
    maintainer: jmpsec/osctrl
    description: osctrl API component
    homepage: https://github.com/jmpsec/osctrl
    license: MIT
    formats:
      - deb
    bindir: /opt/osctrl/bin
    contents:
      - src: ./dist/osctrl-api-{{ .Os }}-{{ .Arch }}
        dst: /opt/osctrl/bin/osctrl-api
    overrides:
      deb:
        scripts:
          postinstall: deploy/cicd/deb/post-install.sh
          preremove: deploy/cicd/deb/pre-remove.sh

  - id: osctrl-cli
    maintainer: jmpsec/osctrl
    description: osctrl CLI component
    homepage: https://github.com/jmpsec/osctrl
    license: MIT
    formats:
      - deb
    bindir: /opt/osctrl/bin
    contents:
      - src: ./dist/osctrl-cli-{{ .Os }}-{{ .Arch }}
        dst: /opt/osctrl/bin/osctrl-cli
    overrides:
      deb:
        scripts:
          postinstall: deploy/cicd/deb/post-install.sh
          preremove: deploy/cicd/deb/pre-remove.sh

release:
  draft: false
  prerelease: false
