FROM golang:latest
LABEL maintainer="javuto"

ADD deploy/docker/admin.json /go/config

ADD deploy/data/3.3.0.json /go/data

ADD static /go/static
ADD templates/ /go/templates

RUN go build -o osctrl-admin /go/*.go

EXPOSE 9001

CMD ["./osctrl-admin"]
