ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}

ARG AIR_VERSION=1.29.0
ARG OSQUERY_VERSION=5.2.2

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y git \
    make openssh-client \
    curl

WORKDIR /app 

RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/v${AIR_VERSION}/install.sh \
    && chmod +x install.sh \
    && sh install.sh \
    && cp ./bin/air /bin/air

COPY deploy/docker/conf/air/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]