FROM ubuntu:20.04
RUN useradd -ms /usr/sbin/nologin osctrl
RUN mkdir -p /opt/osctrl/bin
RUN mkdir -p /opt/osctrl/scripts
RUN mkdir -p /opt/osctrl/config
COPY osctrl-tls.bin /opt/osctrl/bin/osctrl-tls
USER osctrl
WORKDIR /opt/osctrl
EXPOSE 9000/tcp
CMD ["/opt/osctrl/bin/osctrl-tls"]