FROM ubuntu:20.04

ARG COMPONENT
ARG GOOS
ARG GOARCH

RUN useradd -ms /usr/sbin/nologin osctrl-${COMPONENT}
RUN mkdir -p /opt/osctrl/bin
COPY osctrl-${COMPONENT}-${GOOS}-${GOARCH}.bin /opt/osctrl/bin/osctrl-${COMPONENT}
USER osctrl-${COMPONENT}
WORKDIR /opt/osctrl
CMD [ "/opt/osctrl/bin/wait-cli.sh" ]