# Config file for [Air](https://github.com/cosmtrek/air) in TOML format for osctrl-admin

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "."
tmp_dir = "/tmp"

[build]
  bin = "./bin/osctrl-admin"
  pre_cmd = ["cp -R /usr/src/app/cmd/admin/templates/ /opt/osctrl/tmpl_admin", "cp -R /usr/src/app/cmd/admin/static/ /opt/osctrl/static"]
  cmd = "go build -ldflags \"-s -w -X main.buildCommit=$(git rev-parse HEAD) -X main.buildCommit=$(date -u +%Y-%m-%dT%H:%M:%SZ)\" -o /opt/osctrl/bin/osctrl-admin /usr/src/app/cmd/admin/*.go"
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata", "deploy", "api", "cli", "tls"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "cd /opt/osctrl && ./bin/osctrl-admin"
  include_dir = []
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
