FROM ubuntu:22.04

ARG COMPONENT=admin
ARG GOOS=linux
ARG GOARCH=amd64

RUN apt-get update -y -q && \
    apt-get install -y -q --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /usr/sbin/nologin osctrl-${COMPONENT}
RUN mkdir -p /opt/osctrl/bin \
    /opt/osctrl/config \
    /opt/osctrl/tmpl_admin/components \
    /opt/osctrl/static \
    /opt/osctrl/data \
    /opt/osctrl/carved_files && \
    chown -R osctrl-${COMPONENT}:osctrl-${COMPONENT} /opt/osctrl

COPY osctrl-${COMPONENT}-${GOOS}-${GOARCH} /opt/osctrl/bin/osctrl-${COMPONENT}
RUN chmod 0755 /opt/osctrl/bin/osctrl-${COMPONENT}

# GoReleaser extra_files provides these paths in the docker build context.
COPY templates/ /opt/osctrl/tmpl_admin
COPY static/ /opt/osctrl/static
COPY data/*.json /opt/osctrl/data/

USER osctrl-${COMPONENT}
WORKDIR /opt/osctrl
EXPOSE 9001/tcp
CMD ["/opt/osctrl/bin/osctrl-admin"]
