FROM ubuntu:22.04

ARG COMPONENT=cli
ARG GOOS=linux
ARG GOARCH=amd64

RUN apt-get update -y -q && \
    apt-get install -y -q --no-install-recommends ca-certificates bash && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /usr/sbin/nologin osctrl-${COMPONENT}
RUN mkdir -p /opt/osctrl/bin \
    /opt/osctrl/config && \
    chown -R osctrl-${COMPONENT}:osctrl-${COMPONENT} /opt/osctrl

COPY osctrl-${COMPONENT}-${GOOS}-${GOARCH} /opt/osctrl/bin/osctrl-${COMPONENT}
RUN chmod 0755 /opt/osctrl/bin/osctrl-${COMPONENT}

USER osctrl-${COMPONENT}
WORKDIR /opt/osctrl
ENTRYPOINT ["/bin/bash"]
