FROM ubuntu:22.04

ARG COMPONENT=admin
ARG GOOS=linux
ARG GOARCH=amd64

RUN apt-get update -y -q && \
    apt-get install -y -q --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /usr/sbin/nologin osctrl-${COMPONENT}
RUN mkdir -p /opt/osctrl/bin \
    /opt/osctrl/config \
    /opt/osctrl/tmpl_admin/components \
    /opt/osctrl/static/css \
    /opt/osctrl/static/js \
    /opt/osctrl/static/fonts \
    /opt/osctrl/static/img \
    /opt/osctrl/data \
    /opt/osctrl/carved_files && \
    chown -R osctrl-${COMPONENT}:osctrl-${COMPONENT} /opt/osctrl

COPY osctrl-${COMPONENT}-${GOOS}-${GOARCH} /opt/osctrl/bin/osctrl-${COMPONENT}
RUN chmod 0755 /opt/osctrl/bin/osctrl-${COMPONENT}

# GoReleaser extra_files are flattened in the docker build context.
COPY *.html /opt/osctrl/tmpl_admin/
COPY page-*.html /opt/osctrl/tmpl_admin/components/
COPY *.css /opt/osctrl/static/css/
COPY *.js /opt/osctrl/static/js/
COPY *.eot *.ttf *.woff *.woff2 /opt/osctrl/static/fonts/
COPY *.png *.svg /opt/osctrl/static/img/
COPY *.json /opt/osctrl/data/

USER osctrl-${COMPONENT}
WORKDIR /opt/osctrl
EXPOSE 9001/tcp
CMD ["/opt/osctrl/bin/osctrl-admin"]
