FROM ubuntu:22.04

ARG COMPONENT=tls
ARG GOOS=linux
ARG GOARCH=amd64

# Install software
RUN apt-get update -y -q && \
    rm -rf /var/lib/apt/lists/*

# Install/Setup osctrl
RUN useradd -ms /usr/sbin/nologin osctrl-${COMPONENT}
RUN mkdir -p /opt/osctrl/bin && \
    mkdir -p /opt/osctrl/config && \
    mkdir -p /opt/osctrl/script && \
    chown osctrl-${COMPONENT}:osctrl-${COMPONENT} -R /opt/osctrl
COPY osctrl-${COMPONENT}-${GOOS}-${GOARCH}.bin /opt/osctrl/bin/osctrl-${COMPONENT}
RUN chmod 755 /opt/osctrl/bin/osctrl-${COMPONENT}
USER osctrl-${COMPONENT}
WORKDIR /opt/osctrl
EXPOSE 9000/tcp
CMD ["/opt/osctrl/bin/osctrl-tls"]
