######################################## Osctrl-base ########################################
FROM golang:latest AS osctrl-base
ARG OSCTRL_VERSION

ENV GO111MODULE=on

# Install software
RUN apt-get update -y && apt-get install zip curl -y

# Download osctrl version
RUN cd /tmp && \
    curl -L https://github.com/jmpsec/osctrl/archive/refs/tags/${OSCTRL_VERSION}.zip --output osctrl_${OSCTRL_VERSION}.zip && \
    mkdir -p /tmp/osctrl && \
    unzip osctrl_${OSCTRL_VERSION}.zip -d /go/src && \
    mv /go/src/osctrl-${OSCTRL_VERSION} /go/src/osctrl
WORKDIR /go/src/osctrl

########## Compile Osctrl bins ##########
RUN go build -o bin/osctrl-tls tls/*.go
RUN go build -o bin/osctrl-api api/*.go
RUN go build -o bin/osctrl-admin admin/*.go
RUN go build -o bin/osctrl-cli cli/*.go

######################################## Osctrl-tls ########################################
FROM ubuntu:20.04 AS osctrl-tls

ARG POSTGRES_DB_NAME
ARG POSTGRES_DB_USERNAME
ARG POSTGRES_DB_PASSWORD
ARG JWT_SECRET

### Create user ###
RUN useradd -ms /bin/bash osctrl-tls

### Copy osctrl-tls bin and configs ###
RUN mkdir -p /opt/osctrl-tls/{bin,scripts,config}
COPY --from=osctrl-base /go/src/osctrl/bin/osctrl-tls /opt/osctrl-tls/bin/osctrl-tls
COPY --from=osctrl-base /go/src/osctrl/tls/scripts/ /opt/osctrl-tls/scripts
COPY conf/osctrl/tls/tls.json /opt/osctrl-tls/config/tls.json
COPY conf/osctrl/db.json /opt/osctrl-tls/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_NAME }}#${POSTGRES_DB_NAME}#g" /opt/osctrl-tls/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_USERNAME }}#${POSTGRES_DB_USERNAME}#g" /opt/osctrl-tls/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_PASSWORD }}#${POSTGRES_DB_PASSWORD}#g" /opt/osctrl-tls/config/db.json

USER osctrl-tls
EXPOSE 9000
WORKDIR /opt/osctrl-tls

ENTRYPOINT [ "/opt/osctrl-tls/bin/osctrl-tls" ]

######################################## Osctrl-api ########################################
FROM ubuntu:20.04 AS osctrl-api

ARG POSTGRES_DB_NAME
ARG POSTGRES_DB_USERNAME
ARG POSTGRES_DB_PASSWORD
ARG JWT_SECRET

### Create user ###
RUN useradd -ms /bin/bash osctrl-api

### Copy osctrl-api bin and configs ###
RUN mkdir -p /opt/osctrl-api/{bin,config}
COPY --from=osctrl-base /go/src/osctrl/bin/osctrl-api /opt/osctrl-api/bin/osctrl-api

COPY conf/osctrl/api/api.json /opt/osctrl-api/config/api.json
COPY conf/osctrl/jwt.json /opt/osctrl-api/config/jwt.json
RUN sed -i "s#{{ JWT_SECRET }}#${JWT_SECRET}#g" /opt/osctrl-api/config/jwt.json

COPY conf/osctrl/db.json /opt/osctrl-api/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_NAME }}#${POSTGRES_DB_NAME}#g" /opt/osctrl-api/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_USERNAME }}#${POSTGRES_DB_USERNAME}#g" /opt/osctrl-api/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_PASSWORD }}#${POSTGRES_DB_PASSWORD}#g" /opt/osctrl-api/config/db.json
RUN cat /opt/osctrl-api/config/db.json

USER osctrl-api
EXPOSE 9002
WORKDIR /opt/osctrl-api

ENTRYPOINT [ "/opt/osctrl-api/bin/osctrl-api" ]

######################################## Osctrl-admin ########################################
FROM ubuntu:20.04 AS osctrl-admin
ARG OSQUERY_VERSION
ARG POSTGRES_DB_NAME
ARG POSTGRES_DB_USERNAME
ARG POSTGRES_DB_PASSWORD
ARG JWT_SECRET
ARG ENV

### Create user ###
RUN useradd -ms /bin/bash osctrl-admin

### Copy osctrl-admin bin and configs ###
RUN mkdir -p /opt/osctrl-admin/{bin,configs}
COPY --from=osctrl-base /go/src/osctrl/bin/osctrl-admin /opt/osctrl-admin/bin/osctrl-admin
COPY --from=osctrl-base /go/src/osctrl/bin/osctrl-cli /opt/osctrl-admin/bin/osctrl-cli

COPY conf/osctrl/admin/admin.json /opt/osctrl-admin/config/admin.json
COPY conf/osctrl/jwt.json /opt/osctrl-admin/config/jwt.json
RUN sed -i "s#{{ JWT_SECRET }}#${JWT_SECRET}#g" /opt/osctrl-admin/config/jwt.json

COPY conf/osctrl/db.json /opt/osctrl-admin/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_NAME }}#${POSTGRES_DB_NAME}#g" /opt/osctrl-admin/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_USERNAME }}#${POSTGRES_DB_USERNAME}#g" /opt/osctrl-admin/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_PASSWORD }}#${POSTGRES_DB_PASSWORD}#g" /opt/osctrl-admin/config/db.json
RUN chown osctrl-admin:osctrl-admin -R /opt/osctrl-admin/config

### Copy osctrl-admin web templates ###
COPY --from=osctrl-base /go/src/osctrl/admin/templates/ /opt/osctrl-admin/tmpl_admin
COPY --from=osctrl-base /go/src/osctrl/admin/templates/components/page-head-online.html /opt/osctrl-admin/tmpl_admin/components/page-head.html
COPY --from=osctrl-base /go/src/osctrl/admin/templates/components/page-js-online.html /opt/osctrl-admin/tmpl_admin/components/page-js.html
COPY --from=osctrl-base /go/src/osctrl/admin/static/ /opt/osctrl-admin/static
COPY --from=osctrl-base /go/src/osctrl/deploy/osquery/data/${OSQUERY_VERSION}.json /opt/osctrl-admin/data/${OSQUERY_VERSION}.json

RUN mkdir -p /opt/osctrl-admin/carved_files
RUN chown osctrl-admin:osctrl-admin -R /opt/osctrl-admin/carved_files
COPY --from=osctrl-base /go/src/osctrl/deploy/docker/admin/wait.sh /opt/osctrl-admin/wait.sh
RUN chmod +x /opt/osctrl-admin/wait.sh

USER osctrl-admin
EXPOSE 9001
WORKDIR /opt/osctrl-admin
CMD [ "/bin/sh", "/opt/osctrl-admin/wait.sh" ]

######################################## Osctrl-cli ########################################
FROM ubuntu:20.04 AS osctrl-cli
ARG POSTGRES_DB_NAME
ARG POSTGRES_DB_USERNAME
ARG POSTGRES_DB_PASSWORD

### Copy osctrl-admin bin and configs ###
RUN mkdir -p /opt/osctrl-cli/
COPY --from=osctrl-base /go/src/osctrl/bin/osctrl-cli /opt/osctrl-cli/bin/osctrl-cli

COPY conf/osctrl/db.json /opt/osctrl-cli/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_NAME }}#${POSTGRES_DB_NAME}#g" /opt/osctrl-cli/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_USERNAME }}#${POSTGRES_DB_USERNAME}#g" /opt/osctrl-cli/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_PASSWORD }}#${POSTGRES_DB_PASSWORD}#g" /opt/osctrl-cli/config/db.json
RUN ln -s /opt/osctrl-cli/bin/osctrl-cli /usr/local/bin/osctrl-cli

ENTRYPOINT [ "/bin/bash" ]

######################################## Ubuntu node ########################################
FROM ubuntu:20.04 as osctrl-ubuntu-osquery
ARG OSCTRL_VERSION
ARG OSQUERY_VERSION
ARG POSTGRES_DB_NAME
ARG POSTGRES_DB_USERNAME
ARG POSTGRES_DB_PASSWORD

### Copy osctrl-cli bin and config ###
RUN mkdir -p /opt/osctrl-cli/
COPY --from=osctrl-base /go/src/osctrl/bin/osctrl-cli /opt/osctrl-cli/bin/osctrl-cli
COPY conf/osquery/wait.sh /opt/osctrl-cli/bin/wait.sh
RUN chmod +x /opt/osctrl-cli/bin/wait.sh

COPY conf/osctrl/db.json /opt/osctrl-cli/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_NAME }}#${POSTGRES_DB_NAME}#g" /opt/osctrl-cli/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_USERNAME }}#${POSTGRES_DB_USERNAME}#g" /opt/osctrl-cli/config/db.json
RUN sed -i "s#{{ POSTGRES_DB_PASSWORD }}#${POSTGRES_DB_PASSWORD}#g" /opt/osctrl-cli/config/db.json

### Install osquery ###
RUN apt update && apt install -y curl
RUN curl "https://pkg.osquery.io/deb/osquery_${OSQUERY_VERSION}_1.linux.$(dpkg --print-architecture).deb" -o "/tmp/osquery.deb"
RUN dpkg -i "/tmp/osquery.deb"
COPY conf/tls/*.crt /etc/osquery/osctrl.crt

ENTRYPOINT [ "/opt/osctrl-cli/bin/wait.sh" ]