FROM ubuntu:20.04

ARG COMPONENT=cli
ARG GOOS=linux
ARG GOARCH=amd64


RUN useradd -ms /usr/sbin/nologin osctrl-${COMPONENT}
RUN mkdir -p /opt/osctrl/bin && \
    mkdir -p /opt/osctrl/scripts && \
    mkdir -p /opt/osctrl/config && \
    chown osctrl-${COMPONENT}:osctrl-${COMPONENT} -R /opt/osctrl
COPY osctrl-${COMPONENT}-${GOOS}-${GOARCH}.bin /opt/osctrl/bin/osctrl-${COMPONENT}
COPY deploy/docker/conf/osquery/wait-cli.sh /opt/osctrl/scripts/wait-cli.sh
RUN chmod 755 /opt/osctrl/bin/osctrl-${COMPONENT}
RUN chmod 755 /opt/osctrl/scripts/wait-cli.sh
USER osctrl-${COMPONENT}
WORKDIR /opt/osctrl
CMD [ "/opt/osctrl/scripts/wait-cli.sh" ]