FROM ubuntu:20.04

ARG COMPONENT=api
ARG GOOS=linux
ARG GOARCH=amd64


RUN useradd -ms /usr/sbin/nologin osctrl-${COMPONENT}
RUN mkdir -p /opt/osctrl/bin && \
    mkdir -p /opt/osctrl/scripts && \
    mkdir -p /opt/osctrl/config
COPY osctrl-${COMPONENT}-${GOOS}-${GOARCH}.bin /opt/osctrl/bin/osctrl-${COMPONENT}
RUN chmod 755 /opt/osctrl/bin/osctrl-${COMPONENT}
USER osctrl-${COMPONENT}
WORKDIR /opt/osctrl
EXPOSE 9002/tcp
CMD ["/opt/osctrl/bin/osctrl-api"]