name: Go linting on PRs pushed to osctrl

on:
  pull_request:
    branches: [main, master, develop]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/golangci-lint.yml"

permissions:
  contents: read

env:
  GOLANG_VERSION: 1.24.3

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      ########################### Checkout code ###########################
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      ########################### Set up Go ###############################
      - name: Set up Go
        uses: actions/setup-go@8e57b58e57be52ac95949151e2777ffda8501267 # v5.5.0
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
          cache: true

      ########################### Run golangci-lint #######################
      - name: golangci-lint
        uses: golangci/golangci-lint-action@e60da84bfae8c7920a47be973d75e15710aa8bd7 # v8.0.0
        with:
          version: latest
          working-directory: ./
          args: --timeout=5m
          only-new-issues: true
